import Head from 'next/head';
import Image from 'next/image';

import Banner from '../components/banner';
import Card from '../components/card';

import styles from '../styles/Home.module.css';

import coffeeStores from '../data/coffee-stores.json';

const Home = () => {
  const handleBannerButtonClick = () => {
    console.log('hello banner button');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={'View stores nearby'}
          handleClick={handleBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="Image of a girl drinking coffee"
          />
        </div>
        <div className={styles.cardLayout}>
          {coffeeStores.map((c) => {
            return (
              <Card
                key={c.name}
                className={styles.card}
                name={c.name}
                imgUrl={c.imgUrl}
                href={`/coffee-store/${c.id}`}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default Home;
